server:
  port: 0
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/springmicroservices
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: 'event:io.jotech.notificationservice.event.OrderPlacedEvent'

    template:
      default-topic: notificationTopic

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0