spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/springmicroservices
    password: Ur@$2022
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: product-service

server:
  port: 0
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0